### ISSUE TITLE
Get authentication working

### ISSUE THREAD

**Issue by lizbaillie** [lizbaillie/assemble-api#1]
In the `authenticate_user_from_token!` method in the `ApplicationController`, it seems that the params never include the user's authentication token, so all requests are unauthorized. I am attempting to implement token authentication using Devise with Ember Simple Auth on the [front-end](https://github.com/lizbaillie/assemble). I have been using [this strategy](https://gist.github.com/josevalim/fb706b1e933ef01e4fb6).

You can see what I mean by adding a `binding.pry` to the first line of `authenticate_user_from_token!` and attempting to log in. When you hit the binding, you can see that the params do not include the token, ever.

**Comment by ryanlabouve** [comment]
I'm going to leave my long-form notes to make sure I'm understanding the issue correctly. If this is not what you are asking feel free to let me know!

------

Yo! Taking a look at this. 

Kinda taking notes as I go...

So, we are making our initial `POST` to `/users/sign_in`...
* We hit [authenticate_user_from_token!](https://github.com/lizbaillie/assemble-api/blob/master/app/controllers/application_controller.rb#L12), but we have no user token, so it doesn't do anything.
* We then hit the devise action [authenticate_user!](https://github.com/lizbaillie/assemble-api/blob/master/app/controllers/application_controller.rb#L5)... which calls [this in devise](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/sessions_controller.rb#L16)

At this point the call returns `201` and returns `{"token":"sq93bm9xkZWeJjSKMjZg","email":"test@user.com","user_id":5}`.

And we can verify that simple auth is correctly storing the token by checking `ember_simple_auth-session` key in local storage. :yey:

* ~ * ~ * ~

Next, we immediately call `http://localhost:3000/users/me` which returns a `500`.

Looking at the network tab, I do not see us sending a token along with the request

![https://gifcannon.s3.amazonaws.com/Assemble.png](https://gifcannon.s3.amazonaws.com/Assemble.png)

Hoping over to that call in Emberland, I'm checking to make sure we are using the `DataAdapterMixin`, which [we are](https://github.com/lizbaillie/assemble/blob/master/app/adapters/application.js#L6)!  So this should attach all of the header info to all requests we make through Ember Data. So I'm going to find the call we make to [`/me`](So, I think this arrives us at the issue: https://github.com/lizbaillie/assemble/blob/89a0be2c4d3f024f3647d19aa760dbf7f4144778/app/services/session.js#L10
).

So, I think this arrives us at the issue. Devise is expecting for this to be an authenticated request, but since we are not using Ember Data to automagically attach the headers, we would have to do it manually [here](https://github.com/lizbaillie/assemble/blob/89a0be2c4d3f024f3647d19aa760dbf7f4144778/app/services/session.js#L10
).

Something like: 
```
// ESA docs: http://ember-simple-auth.com/api/classes/DeviseAuthorizer.html on this method
this.get('session').authorize('authorizer:application', (headerName, headerValue) => {
  const headers = {};
  // this should be the token stored in ESA
  headers[headerName] = headerValue;
  const promise = Ember.$.ajax("http://localhost:3000/users/me", {
        headers,
        method: 'GET'
   });
   ...
});
```

**Comment by lizbaillie** [comment]
Turns out this was indeed part of the problem, so I started by using Ember Data instead of a plain AJAX request. I couldn't seem to find a way to get it to make a request to any actions outside of typical CRUD actions, so I added some parameters to a request to `users#index`:

```
// services/session.js

  currentUser: Ember.computed('isAuthenticated', function() {
    if (this.get('isAuthenticated')) {
      const promise = this.get('store').queryRecord('user', { current_user: 'true' });
      return DS.PromiseObject.create({ promise: promise });
    }
  })
```

Then, on the Rails side, I added this to my `users#index` action:

```
  def index
    # a bit of a hack to return the current_user for Ember's session service
    # apparently no way to hit `users#me` via Ember Data directly, only via AJAX
    # we lose the auth headers from ESA if we don't go through Ember Data
    if params[:current_user] == 'true'
      render json: current_user
    else
      @users = User.all
      @team = Team.find(user_params["team_id"]) if user_params["team_id"]

      render json: { users: @team ? @team.users : @users }
    end
  end
```
This worked at getting the auth token in the header, but very very weirdly. It looked something like:

`Authorization: "Token token="333", email="wu@tang.org""`

Which is pretty strange. It should just be "333."

I will most likely go back later and fork ESA to hack the bit that's causing that (I assume that's where it's coming from) so the auth header comes through properly, but since I didn't really have time and wanted to just make it work, I added this bit to my `ApplicationController#authenticate_user_from_token!` method:

```
  def authenticate_user_from_token!
    user_token = response.request.env["HTTP_AUTHORIZATION"].split('"')[1] if response.request.env["HTTP_AUTHORIZATION"].presence
    user       = user_token.presence && User.find_by_authentication_token(user_token.to_s)

    if user
      sign_in user
    end
  end
```

A pretty hacky solution for now, but it works!
